/* ============================================
   FlipperUSB Editor - Enhanced Version
   ============================================ */

const DEBUG = true;

// Debug logging with toast integration
const debugLog = {
    log: function (message, type = 'info') {
        if (!DEBUG) return;

        const consoleOutput = document.getElementById('consoleOutput');
        if (consoleOutput) {
            const timestamp = new Date().toLocaleTimeString();
            const logEntry = document.createElement('div');
            logEntry.className = type;
            logEntry.textContent = `[${timestamp}] ${message}`;
            consoleOutput.appendChild(logEntry);
            consoleOutput.scrollTop = consoleOutput.scrollHeight;
        }

        // Also log to browser console
        console.log(`[${type.toUpperCase()}] ${message}`);
    },
    error: function (message) {
        this.log(message, 'error');
    },
    warning: function (message) {
        this.log(message, 'warning');
    },
    success: function (message) {
        this.log(message, 'success');
    },
    info: function (message) {
        this.log(message, 'info');
    }
};

// State
let flipper = new FlipperSerial();
let currentFile = null;
let currentPath = '/';
let hasUnsavedChanges = false;
let allFiles = []; // Cache for search filtering
let isFileExplorerOpen = true;
const serialSupported = 'serial' in navigator;
let lastSavedContent = '';
const DRAFT_STORAGE_PREFIX = 'flipperusb:draft:';
const TEMPLATE_LIBRARY = {
    badusb: [
        {
            value: 'blank',
            label: 'Blank Script',
            description: 'Start with an empty text file.',
            extension: '.txt',
            content: ''
        },
        {
            value: 'notepad',
            label: 'Open Notepad',
            description: 'Quick demo payload for Windows machines.',
            extension: '.txt',
            content: 'REM Generated by FlipperUSB\nDELAY 1000\nGUI r\nDELAY 350\nSTRING notepad\nENTER\n'
        },
        {
            value: 'powershell',
            label: 'PowerShell Starter',
            description: 'Launches PowerShell with a visible prompt.',
            extension: '.txt',
            content: 'REM Generated by FlipperUSB\nDELAY 1000\nGUI x\nDELAY 300\nSTRING i\nDELAY 250\nSTRING powershell\nENTER\n'
        }
    ],
    nfc: [
        {
            value: 'blank',
            label: 'Blank NFC File',
            description: 'Create an empty NFC file.',
            extension: '.nfc',
            content: ''
        },
        {
            value: 'starter',
            label: 'NFC Starter',
            description: 'Adds the basic fields used by Flipper NFC files.',
            extension: '.nfc',
            content: 'Filetype: Flipper NFC device\nVersion: 4\n# UID:\n# ATQA:\n# SAK:\n# Mifare Classic type:\n'
        }
    ],
    subghz: [
        {
            value: 'blank',
            label: 'Blank SubGHz File',
            description: 'Create an empty SubGHz file.',
            extension: '.sub',
            content: ''
        },
        {
            value: 'raw',
            label: 'Raw Signal Starter',
            description: 'Adds common metadata fields for captured signals.',
            extension: '.sub',
            content: 'Filetype: Flipper SubGhz RAW File\nVersion: 1\nFrequency: 433920000\nPreset: FuriHalSubGhzPresetOok650Async\nProtocol: RAW\nRAW_Data:\n'
        }
    ],
    infrared: [
        {
            value: 'blank',
            label: 'Blank Infrared File',
            description: 'Create an empty infrared file.',
            extension: '.ir',
            content: ''
        },
        {
            value: 'signal',
            label: 'IR Signal Starter',
            description: 'Adds the standard IR file header.',
            extension: '.ir',
            content: 'Filetype: IR signals file\nVersion: 1\n#\nname: Example\nprotocol: NEC\naddress: 00 00 00 00\ncommand: 00 00 00 00\n'
        }
    ],
    generic: [
        {
            value: 'blank',
            label: 'Blank File',
            description: 'Start with an empty file.',
            extension: '',
            content: ''
        }
    ]
};

// DOM Elements
const elements = {
    connectBtn: document.getElementById('connectBtn'),
    disconnectBtn: document.getElementById('disconnectBtn'),
    statusIndicator: document.getElementById('statusIndicator'),
    statusText: document.getElementById('statusText'),
    supportText: document.getElementById('supportText'),
    fileList: document.getElementById('fileList'),
    currentPath: document.getElementById('currentPath'),
    parentDir: document.getElementById('parentDir'),
    editor: document.getElementById('editor'),
    editorWelcome: document.getElementById('editorWelcome'),
    currentFile: document.getElementById('currentFile'),
    saveBtn: document.getElementById('saveBtn'),
    downloadBtn: document.getElementById('downloadBtn'),
    newFileBtn: document.getElementById('newFileBtn'),
    newFolderBtn: document.getElementById('newFolderBtn'),
    fileUpload: document.getElementById('fileUpload'),
    fileActions: document.getElementById('fileActions'),
    searchInput: document.getElementById('searchInput'),
    dropZone: document.getElementById('dropZone'),
    fileExplorer: document.getElementById('fileExplorer'),
    mobileMenuToggle: document.getElementById('mobileMenuToggle'),
    consoleOutput: document.getElementById('consoleOutput'),
    toggleConsole: document.getElementById('toggleConsole'),
    clearConsole: document.getElementById('clearConsole')
};

function isConnected() {
    return Boolean(flipper.port);
}

function getDirectoryKind(path = currentPath) {
    if (path.includes('/badusb')) return 'badusb';
    if (path.includes('/nfc')) return 'nfc';
    if (path.includes('/subghz')) return 'subghz';
    if (path.includes('/infrared')) return 'infrared';
    return 'generic';
}

function getTemplateOptions(path = currentPath) {
    return TEMPLATE_LIBRARY[getDirectoryKind(path)] || TEMPLATE_LIBRARY.generic;
}

function getDraftKey(path) {
    return `${DRAFT_STORAGE_PREFIX}${path}`;
}

function getDraftContent(path) {
    if (!path) return null;

    try {
        return localStorage.getItem(getDraftKey(path));
    } catch (error) {
        debugLog.warning(`Draft read failed: ${error.message}`);
        return null;
    }
}

function saveDraftContent(path, content) {
    if (!path) return;

    try {
        localStorage.setItem(getDraftKey(path), content);
    } catch (error) {
        debugLog.warning(`Draft save failed: ${error.message}`);
    }
}

function clearDraftContent(path) {
    if (!path) return;

    try {
        localStorage.removeItem(getDraftKey(path));
    } catch (error) {
        debugLog.warning(`Draft clear failed: ${error.message}`);
    }
}

function syncDraftState() {
    if (!currentFile) return;

    if (elements.editor.value === lastSavedContent) {
        clearDraftContent(currentFile);
    } else {
        saveDraftContent(currentFile, elements.editor.value);
    }
}

function buildPath(basePath, name) {
    return basePath + (basePath.endsWith('/') ? '' : '/') + name;
}

function setCurrentFileLabel(label = 'No file selected', isUnsaved = false) {
    elements.currentFile.innerHTML = `
        <svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
            <polyline points="14 2 14 8 20 8"/>
        </svg>
        ${label}${isUnsaved ? ' <span class="unsaved">●</span>' : ''}
    `;
}

function updateWorkspaceControls() {
    const connected = isConnected();
    elements.searchInput.disabled = !connected;
    elements.searchInput.placeholder = connected
        ? 'Search files...'
        : 'Connect your Flipper to search files';
    elements.parentDir.disabled = !connected || currentPath === '/';
}

function setEditorWelcome(mode) {
    const isUnsupported = !serialSupported;

    if (mode === 'file') {
        elements.editorWelcome.classList.add('hidden');
        elements.editor.classList.remove('hidden');
        return;
    }

    let content = '';

    if (mode === 'connected') {
        content = `
            <div class="editor-welcome-card">
                <div class="welcome-copy">
                    <span class="hero-eyebrow">Ready To Edit</span>
                    <h2>Choose a file or create a new one from the explorer.</h2>
                    <p>Your Flipper is connected. Open an existing file, drag new files into the current folder, or start a fresh payload from the quick actions on the left.</p>
                </div>
                <div class="welcome-grid">
                    <div class="welcome-panel">
                        <strong>BadUSB</strong>
                        <p>Create or tweak scripts in place, then save them straight back to your device.</p>
                    </div>
                    <div class="welcome-panel">
                        <strong>Quick Search</strong>
                        <p>Filter the current directory instantly when you are working inside bigger folders.</p>
                    </div>
                    <div class="welcome-panel">
                        <strong>Safe Flow</strong>
                        <p>Unsaved edits are tracked before you jump to another file or close the page.</p>
                    </div>
                </div>
                <div class="welcome-shortcuts">
                    <span><kbd>Ctrl+S</kbd> Save current file</span>
                    <span><kbd>Ctrl+D</kbd> Download a copy</span>
                    <span><kbd>Ctrl+/</kbd> Focus search</span>
                </div>
            </div>
        `;
    } else {
        content = `
            <div class="editor-welcome-card">
                <div class="welcome-copy">
                    <span class="hero-eyebrow">${isUnsupported ? 'Browser Support' : 'Browser File Manager'}</span>
                    <h2>${isUnsupported ? 'This browser does not support Web Serial.' : 'Manage your Flipper Zero over USB from the browser.'}</h2>
                    <p>${isUnsupported
                        ? 'Open this site in a recent desktop version of Chrome or Edge to connect, browse folders, and edit files directly on your device.'
                        : 'Connect once, then browse your storage, edit scripts inline, upload files with drag and drop, and keep a local backup one click away.'}</p>
                </div>
                <div class="welcome-grid">
                    <div class="welcome-panel">
                        <strong>1. Connect</strong>
                        <p>Start a serial session from the header and grant access to your Flipper Zero.</p>
                    </div>
                    <div class="welcome-panel">
                        <strong>2. Browse</strong>
                        <p>Jump into BadUSB, NFC, SubGHz, or Infrared folders from quick access.</p>
                    </div>
                    <div class="welcome-panel">
                        <strong>3. Edit</strong>
                        <p>Open a file, save changes in place, or download a copy before you experiment.</p>
                    </div>
                </div>
                <div class="welcome-actions">
                    ${isUnsupported ? '' : '<button class="flipper-button" id="editorConnectBtn">Connect Flipper</button>'}
                    <div class="welcome-shortcuts">
                        <span>Desktop Chrome or Edge</span>
                        <span>USB serial workflow</span>
                        <span>No install required</span>
                    </div>
                </div>
            </div>
        `;
    }

    elements.editorWelcome.innerHTML = content;
    elements.editorWelcome.classList.remove('hidden');
    elements.editor.classList.add('hidden');

    const inlineConnectBtn = document.getElementById('editorConnectBtn');
    if (inlineConnectBtn) {
        inlineConnectBtn.addEventListener('click', () => {
            if (!elements.connectBtn.disabled) {
                elements.connectBtn.click();
            }
        });
    }
}

function showRestoreDraftPrompt(path, filename, deviceContent) {
    const draftContent = getDraftContent(path);
    if (draftContent === null || draftContent === deviceContent) {
        return;
    }

    showConfirmModal(
        'Local Draft Found',
        `A newer unsaved draft for "${filename}" was found in this browser. Restore it?`,
        () => {
            elements.editor.value = draftContent;
            hasUnsavedChanges = true;
            setCurrentFileLabel(filename, true);
            toast.info(`Restored draft for ${filename}`);
        },
        () => {
            clearDraftContent(path);
            toast.info(`Discarded saved draft for ${filename}`);
        },
        {
            confirmLabel: 'Restore Draft',
            cancelLabel: 'Discard Draft',
            confirmClass: 'primary'
        }
    );
}

function openCreateFolderModal() {
    showFormModal({
        title: 'Create Folder',
        message: `Create a new folder inside ${currentPath}.`,
        submitLabel: 'Create Folder',
        fields: [
            {
                name: 'folderName',
                label: 'Folder Name',
                placeholder: 'new-folder',
                required: true,
                autofocus: true,
                hint: 'Use a simple folder name without slashes.'
            }
        ],
        onSubmit: async (values) => {
            const folderName = values.folderName.trim();

            if (!folderName || folderName.includes('/')) {
                toast.error('Folder names cannot be empty or contain slashes.');
                return false;
            }

            const path = buildPath(currentPath, folderName);
            const success = await flipper.createDirectory(path);
            if (!success) {
                toast.error(`Failed to create folder: ${folderName}`);
                return false;
            }

            toast.success(`Created folder: ${folderName}`);
            await loadFileList();
            return true;
        }
    });
}

function openCreateFileModal() {
    const templates = getTemplateOptions();
    const suggestedExtension = templates[0]?.extension || '';

    showFormModal({
        title: 'Create File',
        message: `Create a new file inside ${currentPath}.`,
        submitLabel: 'Create File',
        fields: [
            {
                name: 'filename',
                label: 'File Name',
                placeholder: suggestedExtension ? `my-file${suggestedExtension}` : 'my-file.txt',
                required: true,
                autofocus: true,
                hint: suggestedExtension
                    ? `You can omit ${suggestedExtension} and it will be added for you.`
                    : 'Add an extension if you want one.'
            },
            {
                name: 'template',
                label: 'Starter Template',
                type: 'radio',
                value: templates[0]?.value,
                options: templates.map((template) => ({
                    value: template.value,
                    label: template.label,
                    description: template.description
                }))
            }
        ],
        onSubmit: async (values) => {
            const template = templates.find((item) => item.value === values.template) || templates[0];
            const rawFilename = values.filename.trim();

            if (!rawFilename || rawFilename.includes('/')) {
                toast.error('File names cannot be empty or contain slashes.');
                return false;
            }

            const filename = template.extension && !rawFilename.endsWith(template.extension)
                ? `${rawFilename}${template.extension}`
                : rawFilename;
            const path = buildPath(currentPath, filename);

            const success = await flipper.writeFile(path, template.content);
            if (!success) {
                toast.error(`Failed to create file: ${filename}`);
                return false;
            }

            clearDraftContent(path);
            toast.success(`Created: ${filename}`);
            await new Promise((resolve) => setTimeout(resolve, 300));
            await loadFileList();
            await doLoadFile(path);
            return true;
        }
    });
}

// ============================================
// Connection Status
// ============================================

function updateConnectionStatus(status) {
    elements.statusIndicator.className = 'status-dot ' + status;
    elements.statusText.className = 'status-text ' + status;

    const titles = {
        connected: 'Connected to Flipper Zero',
        disconnected: 'Disconnected',
        connecting: 'Connecting...'
    };
    elements.statusIndicator.title = titles[status] || status;
    elements.statusText.textContent = status === 'connected'
        ? 'Connected'
        : status === 'connecting'
            ? 'Connecting'
            : 'Disconnected';
    elements.supportText.textContent = !serialSupported
        ? 'Open this site in desktop Chrome or Edge'
        : status === 'connected'
            ? 'USB serial session active'
            : 'Desktop Chrome or Edge with Web Serial';

    // Update page title
    document.title = status === 'connected'
        ? 'FlipperUSB - Connected'
        : 'FlipperUSB - Web File Manager';

    updateWorkspaceControls();

    switch (status) {
        case 'connected':
            toast.success('Connected to Flipper Zero');
            debugLog.success('Connected to Flipper Zero');
            break;
        case 'disconnected':
            debugLog.warning('Disconnected from Flipper Zero');
            break;
        case 'connecting':
            debugLog.info('Attempting to connect to Flipper Zero...');
            break;
    }
}

// ============================================
// Console Controls
// ============================================

elements.clearConsole.addEventListener('click', () => {
    elements.consoleOutput.innerHTML = '';
    toast.info('Console cleared');
});

elements.toggleConsole.addEventListener('click', (e) => {
    const isHidden = elements.consoleOutput.style.display === 'none';
    elements.consoleOutput.style.display = isHidden ? 'block' : 'none';
    e.currentTarget.querySelector('span').textContent = isHidden ? 'Hide Console' : 'Console';
});

// ============================================
// Mobile Menu Toggle
// ============================================

elements.mobileMenuToggle.addEventListener('click', () => {
    isFileExplorerOpen = !isFileExplorerOpen;
    elements.fileExplorer.classList.toggle('collapsed', !isFileExplorerOpen);

    // Update icon
    const svg = elements.mobileMenuToggle.querySelector('svg');
    if (isFileExplorerOpen) {
        svg.innerHTML = `
            <line x1="3" y1="12" x2="21" y2="12"/>
            <line x1="3" y1="6" x2="21" y2="6"/>
            <line x1="3" y1="18" x2="21" y2="18"/>
        `;
    } else {
        svg.innerHTML = `
            <line x1="18" y1="6" x2="6" y2="18"/>
            <line x1="6" y1="6" x2="18" y2="18"/>
        `;
    }
});

// ============================================
// Connection Handling
// ============================================

elements.connectBtn.addEventListener('click', async () => {
    if (!serialSupported) {
        toast.error('Web Serial is not available in this browser.', {
            title: 'Unsupported Browser'
        });
        return;
    }

    updateConnectionStatus('connecting');
    elements.connectBtn.disabled = true;

    try {
        if (await flipper.connect()) {
            elements.connectBtn.style.display = 'none';
            elements.disconnectBtn.style.display = 'inline-flex';
            updateConnectionStatus('connected');
            setCurrentFileLabel('Choose a file to begin');
            setEditorWelcome('connected');
            await loadFileList();
        } else {
            throw new Error('Connection failed');
        }
    } catch (error) {
        toast.error('Connection failed: ' + error.message, {
            title: 'Connection Error'
        });
        debugLog.error('Connection error: ' + error.message);
        updateConnectionStatus('disconnected');
    } finally {
        elements.connectBtn.disabled = false;
    }
});

elements.disconnectBtn.addEventListener('click', async () => {
    try {
        debugLog.info('Starting disconnect process...');
        await new Promise(resolve => setTimeout(resolve, 100));
        await flipper.disconnect();

        elements.connectBtn.style.display = 'inline-flex';
        elements.disconnectBtn.style.display = 'none';
        updateConnectionStatus('disconnected');

        // Reset to root with quick access
        currentPath = '/';
        elements.currentPath.innerHTML = getPathBreadcrumbs(currentPath);
        renderQuickAccess();

        currentFile = null;
        lastSavedContent = '';
        elements.fileActions.style.display = 'none';

        // Reset editor
        elements.editor.value = '';
        elements.editor.disabled = true;
        elements.saveBtn.disabled = true;
        elements.downloadBtn.disabled = true;
        setCurrentFileLabel('No file selected');
        setEditorWelcome('disconnected');

        toast.info('Disconnected from Flipper');
        debugLog.success('Disconnect completed');
    } catch (error) {
        toast.error('Disconnect error: ' + error.message);
        debugLog.error('Disconnect error: ' + error.message);
    }
});

// ============================================
// File Navigation
// ============================================

elements.parentDir.addEventListener('click', async () => {
    if (currentPath === '/') return;

    const parts = currentPath.split('/').filter(p => p);
    parts.pop();
    currentPath = parts.length ? '/' + parts.join('/') : '/';
    await loadFileList();
});

function getPathBreadcrumbs(path) {
    const parts = path.split('/').filter(p => p);
    let breadcrumbs = '';
    let fullPath = '';

    breadcrumbs += `<span class="breadcrumb-item" data-path="/">root</span>`;
    parts.forEach(part => {
        fullPath += '/' + part;
        breadcrumbs += ` / <span class="breadcrumb-item" data-path="${fullPath}">${part}</span>`;
    });

    return breadcrumbs;
}

// ============================================
// Search Functionality
// ============================================

elements.searchInput.addEventListener('input', (e) => {
    const query = e.target.value.toLowerCase().trim();
    filterFiles(query);
});

function filterFiles(query) {
    const fileItems = document.querySelectorAll('.file-item');
    let visibleCount = 0;

    fileItems.forEach(item => {
        const name = item.querySelector('.name').textContent.toLowerCase();
        const matches = !query || name.includes(query);
        item.style.display = matches ? 'flex' : 'none';
        if (matches) visibleCount++;
    });

    // Show "no results" if nothing matches
    const existingNoResults = document.querySelector('.no-results');
    if (existingNoResults) existingNoResults.remove();

    if (visibleCount === 0 && query) {
        const noResults = document.createElement('div');
        noResults.className = 'empty-dir no-results';
        noResults.innerHTML = `<p>No files matching "${query}"</p>`;
        elements.fileList.appendChild(noResults);
    }
}

// ============================================
// Drag and Drop Upload
// ============================================

const dropEvents = ['dragenter', 'dragover', 'dragleave', 'drop'];

dropEvents.forEach(eventName => {
    elements.fileExplorer.addEventListener(eventName, preventDefaults, false);
});

function preventDefaults(e) {
    e.preventDefault();
    e.stopPropagation();
}

['dragenter', 'dragover'].forEach(eventName => {
    elements.fileExplorer.addEventListener(eventName, () => {
        if (currentPath !== '/') {
            elements.dropZone.style.display = 'flex';
            elements.dropZone.classList.add('active');
        }
    });
});

['dragleave', 'drop'].forEach(eventName => {
    elements.fileExplorer.addEventListener(eventName, () => {
        elements.dropZone.style.display = 'none';
        elements.dropZone.classList.remove('active');
    });
});

elements.fileExplorer.addEventListener('drop', handleDrop);

async function handleDrop(e) {
    if (currentPath === '/') {
        toast.warning('Cannot upload to root directory');
        return;
    }

    const files = e.dataTransfer.files;
    if (files.length === 0) return;

    toast.info(`Uploading ${files.length} file(s)...`);

    for (const file of files) {
        await uploadFile(file);
    }

    await loadFileList();
}

async function uploadFile(file) {
    try {
        const reader = new FileReader();

        return new Promise((resolve, reject) => {
            reader.onload = async (event) => {
                const content = event.target.result;
                const path = currentPath + (currentPath.endsWith('/') ? '' : '/') + file.name;

                if (await flipper.writeFile(path, content)) {
                    toast.success(`Uploaded: ${file.name}`);
                    debugLog.success(`File uploaded: ${path}`);
                    resolve();
                } else {
                    toast.error(`Failed to upload: ${file.name}`);
                    reject(new Error('Upload failed'));
                }
            };
            reader.onerror = () => reject(reader.error);
            reader.readAsText(file);
        });
    } catch (error) {
        toast.error(`Upload error: ${error.message}`);
        debugLog.error(`Upload error: ${error.message}`);
    }
}

// Standard file input upload
elements.fileUpload.addEventListener('change', async (e) => {
    const files = e.target.files;
    if (!files.length) return;

    for (const file of files) {
        await uploadFile(file);
    }

    await loadFileList();
    e.target.value = '';
});

// ============================================
// File List Loading
// ============================================

async function loadFileList(resetScroll = true) {
    const scrollPos = elements.fileList.scrollTop;

    // Update breadcrumb navigation
    elements.currentPath.innerHTML = getPathBreadcrumbs(currentPath);
    updateWorkspaceControls();

    // Add click handlers for breadcrumbs
    document.querySelectorAll('.breadcrumb-item').forEach(item => {
        item.addEventListener('click', async () => {
            currentPath = item.dataset.path;
            await loadFileList();
        });
    });

    // Show loading state
    elements.fileList.innerHTML = `
        <div class="loading">
            <div class="loading-spinner"></div>
            <span>Loading files...</span>
        </div>
    `;

    try {
        const items = await flipper.listDirectory(currentPath);
        elements.fileList.innerHTML = '';
        allFiles = items; // Cache for search

        // Handle root directory - show quick access AND directory listing
        if (currentPath === '/') {
            elements.fileActions.style.display = 'none';
            renderQuickAccess();
            // Also render the directory items below quick access
            renderFileItems(items, true); // true = append mode
        } else {
            elements.fileActions.style.display = 'flex';
            updateNewFileButtonLabel();
            renderFileItems(items, false);
        }
    } catch (error) {
        elements.fileList.innerHTML = `
            <div class="empty-dir error">
                <p>Error loading directory: ${error.message}</p>
                <button class="flipper-button small" onclick="loadFileList()">Retry</button>
            </div>
        `;
        toast.error('Failed to load directory');
        debugLog.error('Directory load error: ' + error.message);
    }

    if (!resetScroll) {
        elements.fileList.scrollTop = scrollPos;
    }

    // Clear search
    elements.searchInput.value = '';
    updateWorkspaceControls();
}

function renderQuickAccess() {
    const connected = isConnected();
    const quickAccessHTML = `
        <section class="explorer-hero">
            <span class="hero-eyebrow">${connected ? 'Flipper Storage' : 'USB Workflow'}</span>
            <h2>${connected ? 'Jump into the folders you use most.' : 'Connect your Flipper and start editing over USB.'}</h2>
            <p>${connected
                ? 'Use quick access to open common content folders fast, or browse the full root directory below.'
                : 'Once connected you can browse storage, upload files, edit scripts in place, and download backups without leaving the browser.'}</p>
            <div class="hero-pills">
                <span>BadUSB payloads</span>
                <span>Drag and drop uploads</span>
                <span>Inline editing</span>
            </div>
        </section>
        <div class="quick-access-header">
            <div>
                <h3>Quick access</h3>
                <p>${connected ? 'Common Flipper Zero directories' : 'Available after you connect your device'}</p>
            </div>
        </div>
        <div class="quick-access">
            <button data-path="/ext/badusb" class="${connected ? '' : 'requires-connection'}">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <rect x="4" y="4" width="16" height="16" rx="2"/>
                    <path d="M9 9h6M9 12h6M9 15h4"/>
                </svg>
                BadUSB
            </button>
            <button data-path="/ext/nfc" class="${connected ? '' : 'requires-connection'}">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <rect x="2" y="4" width="20" height="16" rx="2"/>
                    <path d="M7 15V9l3 3 3-3v6"/>
                    <circle cx="17" cy="12" r="2"/>
                </svg>
                NFC
            </button>
            <button data-path="/ext/subghz" class="${connected ? '' : 'requires-connection'}">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <path d="M5 12.55a11 11 0 0 1 14.08 0"/>
                    <path d="M1.42 9a16 16 0 0 1 21.16 0"/>
                    <path d="M8.53 16.11a6 6 0 0 1 6.95 0"/>
                    <circle cx="12" cy="20" r="1"/>
                </svg>
                SubGHz
            </button>
            <button data-path="/ext/infrared" class="${connected ? '' : 'requires-connection'}">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <circle cx="12" cy="12" r="3"/>
                    <circle cx="12" cy="12" r="6" stroke-dasharray="2 2"/>
                    <circle cx="12" cy="12" r="9" stroke-dasharray="2 2"/>
                </svg>
                Infrared
            </button>
        </div>
    `;

    elements.fileList.innerHTML = quickAccessHTML;

    // Add click handlers
    document.querySelectorAll('.quick-access button').forEach(btn => {
        btn.addEventListener('click', async () => {
            if (!isConnected()) {
                toast.warning('Connect your Flipper first to browse files');
                return;
            }

            currentPath = btn.dataset.path;
            await loadFileList();
        });
    });
}

function renderFileItems(items, appendMode = false) {
    if (items.length === 0 && !appendMode) {
        elements.fileList.innerHTML = `
            <div class="empty-dir">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
                    <path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"/>
                </svg>
                <p>This directory is empty</p>
                <button class="flipper-button small secondary" onclick="document.getElementById('newFileBtn').click()">
                    Create a file
                </button>
            </div>
        `;
        return;
    }

    // If no items in append mode (root), just return - quick access already shown
    if (items.length === 0) return;

    // Sort: directories first, then alphabetically
    const sortedItems = items.sort((a, b) => {
        if (a.type === b.type) return a.name.localeCompare(b.name);
        return a.type === 'directory' ? -1 : 1;
    });

    sortedItems.forEach(item => {
        const div = document.createElement('div');
        div.className = 'file-item';
        if (currentFile === item.path) {
            div.classList.add('active');
        }

        const icon = getFileIcon(item.name, item.type === 'directory');
        const iconClass = item.type === 'directory' ? 'icon folder' : 'icon';

        div.innerHTML = `
            <span class="${iconClass}">${icon}</span>
            <span class="name">${item.name}</span>
            ${item.type === 'file' ? `
                <span class="size">${item.size || ''}</span>
                <button class="download-btn" title="Download">
                    <svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2">
                        <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                        <polyline points="7 10 12 15 17 10"/>
                        <line x1="12" y1="15" x2="12" y2="3"/>
                    </svg>
                </button>
                <button class="delete-btn" title="Delete">
                    <svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2">
                        <polyline points="3 6 5 6 21 6"/>
                        <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/>
                    </svg>
                </button>
            ` : ''}
        `;

        if (item.type === 'directory') {
            div.addEventListener('click', async () => {
                currentPath = item.path;
                await loadFileList();
            });
        } else {
            div.addEventListener('click', (e) => {
                // Don't trigger if clicking action buttons
                if (!e.target.closest('.download-btn') && !e.target.closest('.delete-btn')) {
                    loadFile(item.path);
                }
            });

            // Download button
            const downloadBtn = div.querySelector('.download-btn');
            downloadBtn.addEventListener('click', async (e) => {
                e.stopPropagation();
                await downloadFile(item.path, item.name);
            });

            // Delete button
            const deleteBtn = div.querySelector('.delete-btn');
            deleteBtn.addEventListener('click', async (e) => {
                e.stopPropagation();
                showConfirmModal(
                    'Delete File',
                    `Are you sure you want to delete "${item.name}"?`,
                    async () => {
                        if (await flipper.deleteFile(item.path)) {
                            toast.success(`Deleted: ${item.name}`);
                            clearDraftContent(item.path);
                            if (currentFile === item.path) {
                                currentFile = null;
                                lastSavedContent = '';
                                elements.editor.value = '';
                                elements.editor.disabled = true;
                                elements.saveBtn.disabled = true;
                                elements.downloadBtn.disabled = true;
                                setCurrentFileLabel('Choose a file to begin');
                                setEditorWelcome('connected');
                            }
                            await loadFileList();
                        } else {
                            toast.error('Failed to delete file');
                        }
                    },
                    null,
                    {
                        confirmLabel: 'Delete',
                        confirmClass: 'danger'
                    }
                );
            });
        }

        elements.fileList.appendChild(div);
    });
}

function updateNewFileButtonLabel() {
    const newFileBtn = document.getElementById('newFileBtn');
    const span = newFileBtn.querySelector('span');

    if (currentPath.includes('/badusb')) {
        span.textContent = 'New Script';
    } else if (currentPath.includes('/nfc')) {
        span.textContent = 'New NFC';
    } else if (currentPath.includes('/subghz')) {
        span.textContent = 'New SubGHz';
    } else if (currentPath.includes('/infrared')) {
        span.textContent = 'New IR';
    } else {
        span.textContent = 'New File';
    }
}

// ============================================
// File Operations
// ============================================

async function loadFile(path) {
    // Check for unsaved changes
    if (hasUnsavedChanges) {
        showConfirmModal(
            'Unsaved Changes',
            'You have unsaved changes. Discard them and open this file?',
            async () => {
                hasUnsavedChanges = false;
                await doLoadFile(path);
            },
            null,
            {
                confirmLabel: 'Discard',
                confirmClass: 'primary'
            }
        );
        return;
    }

    await doLoadFile(path);
}

async function doLoadFile(path) {
    debugLog.info(`Loading file: ${path}`);

    // Show loading state
    elements.editor.value = 'Loading...';
    elements.editor.disabled = true;

    const content = await flipper.readFile(path);

    if (content !== null) {
        currentFile = path;
        lastSavedContent = content;
        const filename = path.split('/').pop();
        setCurrentFileLabel(filename);
        elements.editor.value = content;
        elements.editor.disabled = false;
        elements.saveBtn.disabled = false;
        elements.downloadBtn.disabled = false;
        hasUnsavedChanges = false;
        setEditorWelcome('file');

        // Update active state in file list
        document.querySelectorAll('.file-item').forEach(item => {
            item.classList.remove('active');
            if (item.querySelector('.name').textContent === filename) {
                item.classList.add('active');
            }
        });

        toast.success(`Opened: ${filename}`);
        debugLog.success(`File loaded: ${path}`);
        showRestoreDraftPrompt(path, filename, content);

        // On mobile, collapse file explorer after opening file
        if (window.innerWidth <= 768) {
            isFileExplorerOpen = false;
            elements.fileExplorer.classList.add('collapsed');
        }
    } else {
        elements.editor.value = '';
        elements.editor.disabled = true;
        elements.saveBtn.disabled = true;
        elements.downloadBtn.disabled = true;
        lastSavedContent = '';
        setEditorWelcome(isConnected() ? 'connected' : 'disconnected');
        toast.error('Failed to load file');
        debugLog.error(`Failed to load file: ${path}`);
    }
}

// Track unsaved changes
elements.editor.addEventListener('input', () => {
    if (!hasUnsavedChanges && currentFile) {
        hasUnsavedChanges = true;
        const filename = currentFile.split('/').pop();
        setCurrentFileLabel(filename, true);
    }

    syncDraftState();
});

// Save file
elements.saveBtn.addEventListener('click', saveCurrentFile);

async function saveCurrentFile() {
    if (!currentFile) return;

    const content = elements.editor.value;
    const saveBtn = elements.saveBtn;
    const originalHTML = saveBtn.innerHTML;

    saveBtn.disabled = true;
    saveBtn.innerHTML = `
        <div class="loading-spinner" style="width: 14px; height: 14px;"></div>
        <span>Saving...</span>
    `;

    try {
        const success = await flipper.writeFile(currentFile, content);
        if (!success) {
            throw new Error('Save failed');
        }

        hasUnsavedChanges = false;
        lastSavedContent = content;
        const filename = currentFile.split('/').pop();
        setCurrentFileLabel(filename);
        clearDraftContent(currentFile);

        toast.success(`Saved: ${filename}`);
        debugLog.success(`File saved: ${currentFile}`);

        await loadFileList(false);
    } catch (error) {
        toast.error('Failed to save file');
        debugLog.error(`Save error: ${error.message}`);
    } finally {
        saveBtn.innerHTML = originalHTML;
        saveBtn.disabled = false;
    }
}

// Download file
elements.downloadBtn.addEventListener('click', async () => {
    if (currentFile) {
        const filename = currentFile.split('/').pop();
        await downloadFile(currentFile, filename, elements.editor.value);
    }
});

async function downloadFile(path, filename, content = null) {
    try {
        // If content not provided, read from device
        if (content === null) {
            content = await flipper.readFile(path);
            if (content === null) {
                toast.error('Failed to read file for download');
                return;
            }
        }

        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);

        toast.success(`Downloaded: ${filename}`);
    } catch (error) {
        toast.error('Download failed: ' + error.message);
    }
}

// New file
elements.newFileBtn.addEventListener('click', openCreateFileModal);
elements.newFolderBtn.addEventListener('click', openCreateFolderModal);

// ============================================
// Keyboard Shortcuts
// ============================================

document.addEventListener('keydown', (e) => {
    // Ctrl+S - Save
    if (e.ctrlKey && e.key === 's') {
        e.preventDefault();
        if (currentFile && !elements.saveBtn.disabled) {
            saveCurrentFile();
        }
    }

    // Ctrl+D - Download
    if (e.ctrlKey && e.key === 'd') {
        e.preventDefault();
        if (currentFile && !elements.downloadBtn.disabled) {
            elements.downloadBtn.click();
        }
    }

    // Escape - Close mobile menu
    if (e.key === 'Escape') {
        if (window.innerWidth <= 768 && isFileExplorerOpen) {
            isFileExplorerOpen = false;
            elements.fileExplorer.classList.add('collapsed');
        }
    }

    // Ctrl+/ - Focus search
    if (e.ctrlKey && e.key === '/') {
        e.preventDefault();
        elements.searchInput.focus();
    }
});

// ============================================
// Warn on unsaved changes before leaving
// ============================================

window.addEventListener('beforeunload', (e) => {
    if (hasUnsavedChanges) {
        e.preventDefault();
        e.returnValue = '';
    }
});

// ============================================
// Initialize
// ============================================

if (!serialSupported) {
    elements.connectBtn.disabled = true;
    elements.connectBtn.title = 'Open this site in desktop Chrome or Edge';
}

if (serialSupported) {
    navigator.serial.addEventListener('disconnect', async (event) => {
        const disconnectedPort = event.target || event.port;

        if (flipper.port && disconnectedPort === flipper.port) {
            debugLog.warning('Flipper disconnected unexpectedly');
            toast.warning('Flipper disconnected unexpectedly');
            await flipper.disconnect();

            elements.connectBtn.style.display = 'inline-flex';
            elements.disconnectBtn.style.display = 'none';
            currentFile = null;
            currentPath = '/';
            hasUnsavedChanges = false;
            lastSavedContent = '';
            elements.currentPath.innerHTML = getPathBreadcrumbs(currentPath);
            elements.editor.value = '';
            elements.editor.disabled = true;
            elements.saveBtn.disabled = true;
            elements.downloadBtn.disabled = true;
            elements.fileActions.style.display = 'none';
            setCurrentFileLabel('No file selected');
            setEditorWelcome('disconnected');
            renderQuickAccess();
            updateConnectionStatus('disconnected');
        }
    });
}

elements.currentPath.innerHTML = getPathBreadcrumbs(currentPath);
setCurrentFileLabel('No file selected');
setEditorWelcome('disconnected');
renderQuickAccess();
updateConnectionStatus('disconnected');
